name: Android

on:
  pull_request:
    branches:
      - main

jobs:
  test-android-e2e:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Specify node version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: 'openjdk8'
          architecture: 'x64'

      - name: Download Android Emulator Image
        run: |
          echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager --verbose "system-images;android-27;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd -n emu_api_27 -k "system-images;android-27;google_apis;x86" -b "x86" -c 1G -d 7 -f

      - name: Build e2e target
        run: |
          yarn install --frozen-lockfile
          yarn build:android:release

      - name: Android test
        timeout-minutes: 10
        continue-on-error: true
        run: |
          mkdir -p artifacts
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          $ANDROID_HOME/emulator/emulator @emu_api_27 &
          adb wait-for-device; adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'; adb shell wm dismiss-keyguard
          yarn test:android:release
      - name: Upload test artifacts (videos)
        uses: actions/upload-artifact@master
        with:
          name: android-failing-e2e-videos
          path: artifacts/
